---
title: "Instacart Orders In 2017"
author: "Mingming Pan"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(plotly)
library(flexdashboard)
```


```{r data_read, include = FALSE}
#read data
instacart_df <- read_csv("./data/instacart.csv")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A


```{r, warning=FALSE, message=FALSE}
#ggplot 2 visualization of the top 6 aisles in the the top 6 departments by items purchased.
instacart_plot1 <- 
  instacart_df %>% 
  filter(department_id %in% c("4","16","19","7","1","13")) %>%
  group_by(department, aisle) %>%
  summarise(N = n()) %>%
  arrange(department, desc(N)) %>%
  group_by(department) %>%
  slice(1:6) %>%
  ggplot(aes(x = N, y = fct_reorder(aisle, N), fill = department)) +
  geom_bar(stat = "identity") +
  facet_wrap(~department, scales = "free_y", ncol = 1) +
  theme(legend.position = "bottom") +
  labs(
    x = "Number of Items Purchased",
    y = "Name of Aisles",
    title = "The Top 6 Aisles in the Top 6 Departments by Items Purchased")

#ggplotly
ggplotly(instacart_plot1)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
#ggplot 2 which displays the number of orders (of all products) per aisle for top 20 aisle by the number of orders.
instacart_plot2 <- 
  instacart_df %>% 
  distinct(order_id,aisle)  %>%
  group_by(aisle) %>%
  summarise(N = n()) %>%
  slice(1:20) %>%
  ggplot(aes(x = N, y = fct_reorder(aisle, N), fill = aisle)) +
  geom_bar(stat = "identity") + 
  theme(legend.position = "bottom") +
  labs(
    x = "Number of Orders",
    y = "Aisle Name",
    title = "The Number of Orders in  Top 20 Aisles")
#ggplotly
ggplotly(instacart_plot2)
```

### Chart C

```{r, message=FALSE}
#The Top 5 Porducts Purchased in the Top 5 Aisles
instacart_plot3 <-
  instacart_df %>% 
  filter(aisle_id %in% c("83","24","123","120","21")) %>%
  group_by(aisle, product_name) %>%
  summarise(N = n()) %>%
  arrange(aisle, desc(N)) %>%
  group_by(aisle)  %>%
  slice(1:5) %>%
  ggplot(aes(x = N, y = fct_reorder(product_name, N), fill = aisle)) +
  geom_bar(stat = "identity") +
  facet_wrap(~aisle, scales = "free_y", ncol = 1) +
  theme(legend.position = "bottom") +
  labs(
    x = "Number of Items Purchased",
    y = "Name of Products",
    title = "The Top 5 Porducts Purchased in the Top 5 Aisles")
ggplotly(instacart_plot3)
```

