---
title: "Spatial_Dashboard"
author: "Mingming Pan"
date: "4/12/2022"
output: html_document
---

```{r set up, include=FALSE, warning=FALSE}
library(sf)
library(ggmap)
library(tmap)
library(tidycensus)
library(leaflet)
library(osmdata)
library(tigris)
library(tidyverse)
library(ggthemes)
```

#1.2 Please create 1 leaflet of the entire state of MN which contains at least 3 Open Street Maps (osmdata) features of your choice (40pts)
```{r}
#Grab the beauty, clothes, shoes and jewelry
osm_shop_sf.df <- opq(bbox = "hennepin") %>%
             add_osm_feature(key = "shop", value = c("beauty", "clothes", "shoes", "jewelry")) %>%
  osmdata_sf()

#Extract the relevant sf data frame
shop_points.df <- osm_shop_sf.df$osm_points %>% 
  janitor::clean_names() %>%
  filter(!is.na(shop)) %>% #only retain 'valid' tags
  dplyr::select(osm_id, name, shop, opening_hours, phone, website, geometry) %>%
  mutate(shop = str_to_title(shop) %>% as_factor())

#Check it out (minus geometry for display)
shop_points.df %>%
  as_tibble() %>%
  dplyr::select(-geometry) #%>%
  #gt_preview()
```

```{r}
#Get the bounding box and county outline
mn.box           <- osmdata::getbb("minnesota")
hennepin.box     <- osmdata::getbb("hennepin")
hennepin.outline <- osmdata::getbb("hennepin", format_out = "polygon")[[1]] %>%
  as_tibble() %>%
  rename(longitude = V1, latitude = V2)


#Get map from ggmap
#Get the base map (foundational layer)
mn_base.map <- get_map(
                location = hennepin.box,
                source   = "google",
                maptype  = "roadmap",
                crop = TRUE
               )

#Create the base map
hennepin_base.gg <- ggmap(mn_base.map) +
  geom_polygon(data = hennepin.outline, aes(x = longitude, y = latitude), colour = "black", size = 1.6, alpha = 0.1) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )
    
#Display base map
hennepin_base.gg
```

```{r}
#Let's add it to a hennepin_base.gg
hennepin_base.gg +
  geom_sf(data = shop_points.df,
          aes(colour = shop),
          inherit.aes = FALSE,
          alpha = 0.8, shape = 16) +
  labs(title = "Hennepin County, MN OSM Features") + 
  scale_colour_viridis_d("Store") +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )
```

```{r}
#Call viridis library  
library(viridis, quietly = TRUE)

#Extract the levels/order of shop type factor
shop_types <- levels(shop_points.df$shop)
n_types    <- length(shop_types)

#Initialize our colour pallete (discrete in this case)
my_pallete <- colorFactor(viridis_pal(option = "D")(n_types), domain = shop_types)

#Call our leaflet
leaflet(data = shop_points.df) %>%
  addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(
    color   = ~my_pallete(shop_types),
    opacity = 0.4,
    weight  = 2, #outline strength
    radius  = 4 #size of circle
  ) %>%
  addLegend(
    title    = "Store Type",
    position = "bottomright",
    colors   = viridis_pal(option = "D")(n_types),
    labels   = shop_types 
  )
```
```{r}
#Need html tools to get our labels to render appropriately
library(htmltools, quietly = TRUE)

#Add a text label like normal
shop_label.df <- shop_points.df %>%
  mutate(
    text_label = str_c(
                   name,
                   "<br/>Store Type: ",
                   shop,
                   "<br/>Open Hours: ",
                   opening_hours,
                   "<br/>Phone: ",
                   phone,
                   "<br/>Website: ",
                   website
                 )
  )

#Redisplay the leaflet
leaflet(data = shop_label.df) %>%
  addProviderTiles('CartoDB.Positron') %>% 
  addCircleMarkers(
    color   = ~my_pallete(shop_types),
    label   = ~map(text_label, HTML), #map over labels, make html
    opacity = 0.4, #alpha
    weight  = 2, #outline strength
    radius  = 4 #size of circle
  ) %>%
  addLegend(
    title    = "Store Type",
    position = "bottomright",
    colors   = viridis_pal(option = "D")(n_types),
    labels   = shop_types 
  )

```

#1.3 Please create 1 ggplotly of Hennepin County using sf, ggmap, tidycensus, ggplot, and plotly; which describes a Census Blockgroup level 2020 American Community Survey (ACS) esimate/feature of your choosing (25 pts)
```{r}
#Read in the shape file
mn.df <- st_read("./data/USA_Counties/USA_Counties.shp", quiet = TRUE) %>%
  janitor::clean_names() %>%
  filter(state_name == "Minnesota")
```

```{r}
#Install API key
#census_api_key("87a8e368974c8a16a0b035786499e73095bd370e", install = TRUE)

#Save the cache so you don't need to call the same API request over and over
options(tigris_use_cache = TRUE)

#Call the ACS API, returns a sf object
#HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2020 INFLATION-ADJUSTED DOLLARS)
mn_household.df <- get_acs(
  geography = "block group",
  variables = "B19001_001E", #Code for household income
  state     = "27", #Minnesota
  county    = "053", #Hennepin
  year      = 2020,
  geometry  = TRUE
)
```

```{r}
#Add a text label to mn_household.df
mn_household_plotly.df <- mn_household.df %>%
  mutate(
    block_group = str_split(NAME, ",") %>%
                 map_chr(1) %>%
                 str_remove("Block Group "),
    text_label = str_c(
                  "Block group: ",
                  block_group,
                  "\n Household Income: ",
                  scales::dollar(estimate)
                 )
  )

#Generate the ggplot
household.gg <- ggplot() + 
  geom_sf(data = mn_household_plotly.df, 
          aes(fill = estimate, text = text_label),
          colour = "black", size = 0.1) + 
  labs(title = "Hennepin County, MN 2020 ACS Household Income") + 
  scale_fill_viridis_c("Household Income") +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )


#Display
ggplotly(household.gg,
         tooltip = "text",
         height  = 600,
         width   = 800) %>%
    style(hoveron = "fills")

```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```









